--- 
- name : inject secret into .env file
  hosts: jenkins_server
  gather_facts: false
  vars:
    secret: "{{ lookup('env', 'JENKINS_AGENT_SECRET') }}"
  tasks:
    - name: verify secret exists
      ansible.builtin.debug:
        msg: "Secret length: {{ secret | length }}"
    - name : inject secret
      become: true
      ansible.builtin.lineinfile:
        path: /home/ubuntu/.env
        regexp: '^JENKINS_AGENT_SECRET='
        line: 'JENKINS_AGENT_SECRET={{ secret }}'