---
- name: infra setup
  hosts: jenkins_server
  gather_facts: true
  become: false
  tasks:
    - name : copy docker-compose.yaml to remote server
      ansible.builtin.copy:
        src: docker-compose.yaml
        dest: /home/ubuntu/docker-compose.yaml
        owner: ubuntu
        group: ubuntu
        mode: '0644'
    - name : copy .env to remote server
      ansible.builtin.copy:
        src: .env
        dest: /home/ubuntu/.env
        owner: ubuntu
        group: ubuntu
        mode: '0644'
    - name : run docker-compose up
      become: true
      ansible.builtin.shell: |
        cd /home/ubuntu
        docker compose --env-file .env up -d
        