version: "3.8"

services:
  jenkins-blueocean:
    container_name: jenkins-srv
    image: jenkins/jenkins:2.568.1-jdk21
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home:rw
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker    
    networks:
      - jenkins
  agent:
    container_name: build_agent
    image: jenkins/inbound-agent:jdk25
    restart: unless-stopped
    environment:
      JENKINS_URL: http://jenkins-srv:8080
      JENKINS_AGENT_NAME: build_agent
      JENKINS_AGENT_WORKDIR: /home/jenkins/agent
      JENKINS_SECRET: ${JENKINS_AGENT_SECRET}
    volumes:
      - agent_home:/home/jenkins/agent
    networks:
      - jenkins
  sonarqube:
      container_name: sonarqube
      image: sonarqube:lts-community
      restart: unless-stopped
      depends_on:
        - sonar_db
      ports:
        - "9001:9000"
      environment:
        SONAR_JDBC_URL: ${SONARQUBE_JDBC_URL}
        SONAR_JDBC_USERNAME: ${SONAR_JDBC_USERNAME}
        SONAR_JDBC_PASSWORD: ${SONAR_JDBC_PASSWORD}
      volumes:
        - sonarqube_conf:/opt/sonarqube/conf
        - sonarqube_data:/opt/sonarqube/data
        - sonarqube_extensions:/opt/sonarqube/extensions
        - sonarqube_logs:/opt/sonarqube/logs
        - sonarqube_temp:/opt/sonarqube/temp
      networks:
        - jenkins

  sonar_db:
      container_name: sonar_db
      image: postgres:15
      restart: unless-stopped
      environment:
        POSTGRES_USER: ${PG_USER}
        POSTGRES_PASSWORD: ${PG_PASSWORD}
        POSTGRES_DB: sonar
      volumes:
        - sonar_db:/var/lib/postgresql
        - sonar_db_data:/var/lib/postgresql/data
      networks:
        - jenkins

volumes:
  jenkins_home:
  agent_home:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  sonar_db:
  sonar_db_data:

networks:
  jenkins: 
    driver: bridge